### ISSUE TITLE
Make the `note` metadata of models and fields accessible in the templates

### ISSUE THREAD

**Issue by maxmousse** [hapify/hapify#7]
**Is your feature request related to a problem? Please describe.**
The `notes` metada can hold information about the field or the model it is attached to. This could allow to generate comments in the code and documentation. 

**Describe the solution you'd like**
It could be very nice to have access to those `notes` metadata in the templates to automatize comments and documentation generation

**Comment by EdouardDem** [comment]
Feature added in #22 
More details here https://docs.hapify.io/reference/hapify-syntax/#notes
