### ISSUE TITLE
Enrich the metadata describing a relation between to models

### ISSUE THREAD

**Issue by maxmousse** [hapify/hapify#8]
**Is your feature request related to a problem? Please describe.**
Currently, some data are missing to fully describe a relation between to models. When describing a relation, we currently have the next data:
- A way to name the field involved in the relation via the field name.
- A way to target the model involved in the relation via the type entity.
- A way to describe the cardinality of the relation via the tags `oneOne`, `oneMany`, `manyOne`, `manyMany`.

For now, here are some problems I encountered:
- As it is only possible for a relation field to target a model, we are not able to define explicit names for foreign keys. Those can be generated but it can result in long and non-coherent names
- As it is not possible to name a relation explicitly, we must generate relation names that are often long and non-coherent. Those names are required to distinguish to relations between two same models

**Describe the solution you'd like**
It would be nice to have the possibility to fully describe relations by adding a relation name, and be able to specify foreign key names too. That would allow full control on relation and avoid to generate names

**Describe alternatives you've considered**
For now, we are generatind the missing data.

**Comment by EdouardDem** [comment]
This issue should be resolved with this feature #23
